/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bills;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JButton;

/**
 *
 * @author Mypc
 */
public class adminpanel extends javax.swing.JFrame {
    Connection con;
    Statement stmt;
       static int invoicenum=1;
       String textareaset="";
    /**
     * Creates new form adminpanel
     */
    public adminpanel() {
        try
        {
            Class.forName("org.sqlite.JDBC");
             con=DriverManager.getConnection("jdbc:sqlite:test.db");
        }
        catch(Exception e)
        {
            
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Add = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Record = new javax.swing.JButton();
        Billing = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        LogOut = new javax.swing.JButton();
        productcode1 = new javax.swing.JTextField();
        productname1 = new javax.swing.JTextField();
        Unitprice1 = new javax.swing.JTextField();
        enteradd = new javax.swing.JButton();
        cancelaction = new javax.swing.JButton();
        productcode2 = new javax.swing.JTextField();
        okedit = new javax.swing.JButton();
        okdelete = new javax.swing.JButton();
        canceledit = new javax.swing.JButton();
        canceldelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        getContentPane().setLayout(null);

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        getContentPane().add(Add);
        Add.setBounds(70, 20, 120, 30);

        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        getContentPane().add(Edit);
        Edit.setBounds(260, 20, 120, 30);

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete);
        Delete.setBounds(450, 20, 130, 30);

        Record.setText("Record");
        Record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecordActionPerformed(evt);
            }
        });
        getContentPane().add(Record);
        Record.setBounds(640, 20, 130, 30);

        Billing.setText("Billing");
        Billing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillingActionPerformed(evt);
            }
        });
        getContentPane().add(Billing);
        Billing.setBounds(840, 20, 130, 30);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 200, 910, 300);

        LogOut.setText("LogOut");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        getContentPane().add(LogOut);
        LogOut.setBounds(400, 530, 150, 40);

        productcode1.setVisible(false);
        getContentPane().add(productcode1);
        productcode1.setBounds(70, 90, 210, 40);

        productname1.setVisible(false);
        getContentPane().add(productname1);
        productname1.setBounds(330, 90, 340, 40);

        Unitprice1.setVisible(false);
        getContentPane().add(Unitprice1);
        Unitprice1.setBounds(720, 90, 190, 40);

        enteradd.setVisible(false);
        enteradd.setText("OK");
        enteradd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enteraddActionPerformed(evt);
            }
        });
        getContentPane().add(enteradd);
        enteradd.setBounds(940, 90, 150, 40);

        cancelaction.setVisible(false);
        cancelaction.setText("Cancel");
        cancelaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelactionActionPerformed(evt);
            }
        });
        getContentPane().add(cancelaction);
        cancelaction.setBounds(1120, 90, 130, 40);

        productcode2.setVisible(false);
        getContentPane().add(productcode2);
        productcode2.setBounds(440, 90, 160, 40);

        okedit.setVisible(false);
        okedit.setText("OK");
        getContentPane().add(okedit);
        okedit.setBounds(940, 90, 150, 40);

        okdelete.setVisible(false);
        okdelete.setText("OK");
        getContentPane().add(okdelete);
        okdelete.setBounds(940, 90, 150, 40);

        canceledit.setVisible(false);
        canceledit.setText("Cancel");
        getContentPane().add(canceledit);
        canceledit.setBounds(1120, 90, 130, 40);

        canceldelete.setVisible(false);
        canceldelete.setText("Cancel");
        getContentPane().add(canceldelete);
        canceldelete.setBounds(1120, 90, 130, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillingActionPerformed
        // TODO add your handling code here:
        InvoiceForm inv=new InvoiceForm();
        inv.setVisible(true);
        
    }//GEN-LAST:event_BillingActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        login loginf=new login();
        loginf.setVisible(true);
    }//GEN-LAST:event_LogOutActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
       cancelaction.setVisible(true);
        productname1.setVisible(true);
        
        Unitprice1.setVisible(true);
        enteradd.setVisible(true);
        Edit.setEnabled(false);
        Delete.setEnabled(false);
        Record.setEnabled(false);
        Billing.setEnabled(false);
        
        
        
        
    }//GEN-LAST:event_AddActionPerformed

    private void cancelactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelactionActionPerformed
        // TODO add your handling code here:
         productname1.setVisible(false);
         cancelaction.setVisible(false);
        productcode1.setVisible(false);
        Unitprice1.setVisible(false);
        enteradd.setVisible(false);
         Edit.setEnabled(true);
        Delete.setEnabled(true);
        Record.setEnabled(true);
        Billing.setEnabled(true);
    }//GEN-LAST:event_cancelactionActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
        productcode2.setVisible(true);
        enteradd.setVisible(true);
        canceledit.setVisible(true);
         okedit.setVisible(true);
       
         Add.setEnabled(false);
        Delete.setEnabled(false);
        Record.setEnabled(false);
        Billing.setEnabled(false);
    }//GEN-LAST:event_EditActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
         productcode2.setVisible(true);
         canceldelete.setVisible(true);
         okdelete.setVisible(true);
         Edit.setEnabled(false);
        Add.setEnabled(false);
        Record.setEnabled(false);
        Billing.setEnabled(false);
    }//GEN-LAST:event_DeleteActionPerformed

    private void RecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecordActionPerformed
        // TODO add your handling code here:
        try
        {
            
            PreparedStatement pst=con.prepareStatement("select * from products");
            ResultSet rs=pst.executeQuery();
            
            while(rs.next())
            {
                
                
                int productcode1=rs.getInt("productcode");
                String productcode2=Integer.toString(productcode1);
                String productname=rs.getString("productname");
                int unitprice=rs.getInt("unitprice");
                String unitprice1=Integer.toString(unitprice);
                textareaset=textareaset+productcode2+"                                                                          "+productname+"                                                                     "+unitprice1+"                                                                      "+"\n";
                jTextArea1.setText(textareaset);
            }
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
    }//GEN-LAST:event_RecordActionPerformed

    private void enteraddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enteraddActionPerformed
        // TODO add your handling code here:
        String productnameadd=productname1.getText();
        String unitpriceadd=Unitprice1.getText();
        int unitpriceadd1=Integer.parseInt(unitpriceadd);
        try
        {
        stmt=con.createStatement();
        String sql= "INSERT INTO PRODUCTS(PRODUCTNAME,UNITPRICE)" +
                   "VALUES ('"+productnameadd+"','"+unitpriceadd1+"');";
        stmt.executeUpdate(sql);
     
        stmt.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_enteraddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminpanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Billing;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit;
    private javax.swing.JButton LogOut;
    private javax.swing.JButton Record;
    private javax.swing.JTextField Unitprice1;
    private javax.swing.JButton cancelaction;
    private javax.swing.JButton canceldelete;
    private javax.swing.JButton canceledit;
    private javax.swing.JButton enteradd;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton okdelete;
    private javax.swing.JButton okedit;
    private javax.swing.JTextField productcode1;
    private javax.swing.JTextField productcode2;
    private javax.swing.JTextField productname1;
    // End of variables declaration//GEN-END:variables
}
