/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bills;

/**
 *
 * @author Mypc
 */
public class InvoiceForm extends javax.swing.JFrame {

    /**
     * Creates new form InvoiceForm
     */
    static int invoicenum=1;
    public InvoiceForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        invoiceno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        customername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Date = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Mobile = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        productcode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        productname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        unitprice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        subTotal = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        subtotal1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tax = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        discount = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        print = new javax.swing.JButton();
        save = new javax.swing.JButton();
        New = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        productaddbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Invoice No :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 50, 150, 30);

        invoiceno.setEditable(false);
        invoiceno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoicenoActionPerformed(evt);
            }
        });
        getContentPane().add(invoiceno);
        invoiceno.setBounds(150, 50, 240, 30);

        jLabel2.setText("Customer Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 110, 90, 20);
        getContentPane().add(customername);
        customername.setBounds(150, 110, 240, 30);

        jLabel3.setText("Date : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(640, 60, 100, 20);
        getContentPane().add(Date);
        Date.setBounds(760, 60, 290, 30);

        jLabel4.setText("Mobile Number");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(630, 120, 80, 14);
        getContentPane().add(Mobile);
        Mobile.setBounds(760, 110, 290, 30);

        jLabel5.setText("Address :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 180, 100, 20);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(150, 170, 240, 100);

        jLabel6.setText("Product Code");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 290, 100, 20);

        productcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productcodeActionPerformed(evt);
            }
        });
        productcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                productcodeKeyPressed(evt);
            }
        });
        getContentPane().add(productcode);
        productcode.setBounds(140, 310, 110, 30);

        jLabel7.setText("Product Name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(280, 290, 90, 20);

        productname.setVisible(false);
        productname.setEditable(false);
        getContentPane().add(productname);
        productname.setBounds(280, 310, 230, 30);

        jLabel8.setText("Unit Price");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(560, 290, 90, 20);

        unitprice.setVisible(false);
        unitprice.setEditable(false);
        getContentPane().add(unitprice);
        unitprice.setBounds(540, 310, 100, 30);

        jLabel9.setText("Quantity");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(700, 290, 80, 20);

        qty.setVisible(false);
        getContentPane().add(qty);
        qty.setBounds(680, 310, 90, 30);

        jLabel10.setText("Total");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(840, 290, 60, 20);

        subTotal.setVisible(false);
        subTotal.setEditable(false);
        subTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subTotalActionPerformed(evt);
            }
        });
        getContentPane().add(subTotal);
        subTotal.setBounds(810, 310, 100, 30);

        Add.setVisible(false);
        Add.setText("ADD");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        getContentPane().add(Add);
        Add.setBounds(940, 310, 130, 30);

        jLabel11.setText("Subtotal");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(760, 510, 110, 30);

        subtotal1.setEditable(false);
        getContentPane().add(subtotal1);
        subtotal1.setBounds(840, 510, 230, 30);

        jLabel12.setText("Tax");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(770, 560, 60, 20);
        getContentPane().add(tax);
        tax.setBounds(840, 550, 230, 30);

        jLabel13.setText("Discount");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(760, 600, 50, 14);
        getContentPane().add(discount);
        discount.setBounds(840, 590, 230, 30);

        jLabel14.setText("   Total");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(760, 640, 60, 14);
        getContentPane().add(total);
        total.setBounds(840, 630, 230, 30);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(140, 360, 770, 140);

        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print);
        print.setBounds(590, 690, 110, 30);

        save.setText("Save");
        getContentPane().add(save);
        save.setBounds(720, 690, 120, 30);

        New.setText("New");
        getContentPane().add(New);
        New.setBounds(870, 690, 130, 30);

        Exit.setText("Exit");
        getContentPane().add(Exit);
        Exit.setBounds(1020, 690, 130, 30);

        productaddbutton.setText("Check");
        productaddbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productaddbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(productaddbutton);
        productaddbutton.setBounds(940, 310, 130, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productcodeActionPerformed
        // TODO add your handling code here:
        String id=productcode.getText();
        int id1=Integer.parseInt(id);
        productname.setText(id);
        
        
    }//GEN-LAST:event_productcodeActionPerformed
    
    private void subTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subTotalActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_subTotalActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AddActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_printActionPerformed

    private void productcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productcodeKeyPressed
        // TODO add your handling code here:
        String str="";
        str=str+(String)evt.getSource();
        int id=Integer.parseInt(str);
        try
        {
        Class.forName("oracle.jdbc.Driver.OracleDriver");
        
        }
        catch(Exception e)
        {
            
        }
        
    }//GEN-LAST:event_productcodeKeyPressed

    private void invoicenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoicenoActionPerformed
        // TODO add your handling code here:
        String invoicenum1;
        invoicenum1=Integer.toString(invoicenum);
        invoiceno.setText(invoicenum1);
    }//GEN-LAST:event_invoicenoActionPerformed

    private void productaddbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productaddbuttonActionPerformed
        // TODO add your handling code here:
        productname.setVisible(true);
        unitprice.setVisible(true);
        qty.setVisible(true);
        subTotal.setVisible(true);
        Add.setVisible(true);
        
        
    }//GEN-LAST:event_productaddbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JTextField Date;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField Mobile;
    private javax.swing.JButton New;
    private javax.swing.JTextField customername;
    private javax.swing.JTextField discount;
    public javax.swing.JTextField invoiceno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton print;
    private javax.swing.JButton productaddbutton;
    private javax.swing.JTextField productcode;
    private javax.swing.JTextField productname;
    private javax.swing.JTextField qty;
    private javax.swing.JButton save;
    private javax.swing.JTextField subTotal;
    private javax.swing.JTextField subtotal1;
    private javax.swing.JTextField tax;
    private javax.swing.JTextField total;
    private javax.swing.JTextField unitprice;
    // End of variables declaration//GEN-END:variables
}
